int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int is_palindrome(char *s);
int wildcmp(char *s1, char *s2);
int new_sqrt_recursion(int p, int m);
int new_is_prime_number(int p, int m);
int new_is_palindrome(char *p, char *m, int j);
int new_wildcmp(char *s0, char *s, int x);
